package telas;

import atributos.HistoricoProduto;
import atributos.Produto;
import funcoes.Conexao;
import static funcoes.FuncoesDiversas.FormataData;
import funcoes.HistoricoProdutoDAO;
import funcoes.ProdutoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static telas.ExibeProduto.GetIndiceProduto;

/**
 *
 * @author Josy
 */
public final class AlterarEstoque extends javax.swing.JFrame {

    private PreparedStatement pst;
    private int codDetProd;
    private int codFornecedor;
    private int codProduto = GetIndiceProduto();
    private final ExibeProdutos telaExibeProdutos;
    
    /**
     * Creates new form AlterarEstoque
     * @param codDetP
     * @param telaExibeProd
     */
    public AlterarEstoque(int codDetP, ExibeProdutos telaExibeProd) {
        initComponents();
        this.telaExibeProdutos = telaExibeProd;
        codDetProd = codDetP;
        CarregarDadosProduto();
        populaComboBoxFornecedor();
        ocultaCampos();
    }

    public void ocultaCampos() {
        txtDataCadProduto.setVisible(false);
        txtPercentual.setVisible(false);
        jLabData.setVisible(false);
        jLabPercentual.setVisible(false);
        jBtnCalcular.setVisible(false);
        jBtnAdicionar.setVisible(false);
        jBtnConfirmarBaixa.setVisible(false);
        txtPrecoEntrada.setEnabled(false);
        txtPrecoSaida.setEnabled(false);
        txtQuantidade.setVisible(false);
        jLabQuantidade.setVisible(false);
        
    }
    
    public void mostraCampos() {
        txtDataCadProduto.setVisible(true);
        txtPercentual.setVisible(true);
        jLabData.setVisible(true);
        jLabPercentual.setVisible(true);
        jBtnCalcular.setVisible(true);   
        txtPrecoEntrada.setEnabled(true);
        txtPrecoSaida.setEnabled(true);
        txtQuantidade.setEnabled(true);
        txtQuantidade.setVisible(true);
        jLabQuantidade.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQuantMinima = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQuantEstoque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecoEntrada = new javax.swing.JTextField();
        jLabPercentual = new javax.swing.JLabel();
        txtPercentual = new javax.swing.JTextField();
        jBtnCalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPrecoSaida = new javax.swing.JTextField();
        jLabQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabData = new javax.swing.JLabel();
        txtDataCadProduto = new com.toedter.calendar.JDateChooser();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jComboBoxTipoAlteracao = new javax.swing.JComboBox();
        jBtnConfirmarBaixa = new javax.swing.JButton();
        jComboBoxFornecedor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Produto");

        jLabel2.setText("Produto:");

        txtProduto.setEnabled(false);

        jLabel3.setText("Fornecedor:");

        jLabel6.setText("Fabricante:");

        txtFabricante.setEnabled(false);

        jLabel5.setText("Modelo:");

        txtModelo.setEnabled(false);

        jLabel11.setText("Estoque Mínimo:");

        txtQuantMinima.setEnabled(false);

        jLabel10.setText("Estoque Atual:");

        txtQuantEstoque.setEnabled(false);

        jLabel7.setText("Preço de Entrada:");

        txtPrecoEntrada.setEnabled(false);

        jLabPercentual.setText("Percentual:");

        jBtnCalcular.setText("Calcular");
        jBtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularActionPerformed(evt);
            }
        });

        jLabel8.setText("Preço de Saída:");

        txtPrecoSaida.setEnabled(false);

        jLabQuantidade.setText("Quantidade:");

        txtQuantidade.setEnabled(false);

        jLabData.setText("Data:");

        jBtnAdicionar.setText("Adicionar");
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");

        jComboBoxTipoAlteracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o tipo de alteração", "Entrada", "Saída" }));
        jComboBoxTipoAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoAlteracaoActionPerformed(evt);
            }
        });

        jBtnConfirmarBaixa.setText("Confirmar Baixa");
        jBtnConfirmarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarBaixaActionPerformed(evt);
            }
        });

        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o fornecedor" }));
        jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(266, 266, 266)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(txtQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(4, 4, 4)
                            .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(39, 39, 39)
                            .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBtnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAdicionar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnConfirmarBaixa))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabQuantidade)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabData))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtQuantMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtPrecoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabPercentual)))))
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDataCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jBtnCalcular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addGap(5, 5, 5)
                                    .addComponent(txtPrecoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxTipoAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantMinima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addComponent(jLabel10))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnCalcular))
                            .addComponent(txtPrecoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnConfirmarBaixa)
                            .addComponent(jBtnAdicionar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPrecoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabQuantidade))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabData)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularActionPerformed
        float percentual = Float.parseFloat(txtPercentual.getText());
        double precoEntrada = Double.parseDouble(txtPrecoEntrada.getText());
        double resultado = (precoEntrada*percentual)/100;

        txtPrecoSaida.setText(String.valueOf(precoEntrada + resultado));
    }//GEN-LAST:event_jBtnCalcularActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        
        Produto prod = new Produto(); 
        
        int quantAtual = Integer.parseInt(txtQuantEstoque.getText());
        int quantAdicionada = Integer.parseInt(txtQuantidade.getText());
        
        prod.setQuantidade(quantAtual + quantAdicionada);
        prod.setPrecoEntrada(Double.parseDouble(txtPrecoEntrada.getText()));
        prod.setPrecoSaida(Double.parseDouble(txtPrecoSaida.getText()));
        prod.setDataCadProduto(FormataData(txtDataCadProduto.getDate()));
        
        ProdutoDAO.AlterarEstoque(prod, codDetProd);
        
        HistoricoProduto histProduto = new HistoricoProduto();
        
        histProduto.setCodDetProduto(codDetProd);
        histProduto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        histProduto.setValor(Double.parseDouble(txtPrecoEntrada.getText()));
        histProduto.setDataCadProduto(FormataData(txtDataCadProduto.getDate()));
        histProduto.setCodFornecedor(codFornecedor);
        HistoricoProdutoDAO.CadHistoricoProd(histProduto);
        CarregarDadosProduto();
        telaExibeProdutos.TabelaProduto("SELECT * FROM vw_produtos WHERE id_prod = " + codProduto + ";");
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jComboBoxTipoAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoAlteracaoActionPerformed
        
        switch (jComboBoxTipoAlteracao.getSelectedItem().toString()) {
            case "Entrada":
                mostraCampos();
                txtQuantidade.setText("");
                jBtnAdicionar.setVisible(true);
                jBtnConfirmarBaixa.setVisible(false);
                break;
            case "Saída":
                ocultaCampos();
                jBtnConfirmarBaixa.setVisible(true);
                jBtnAdicionar.setVisible(false);
                txtQuantidade.setText("");
                txtQuantidade.setVisible(true);
                txtQuantidade.setEnabled(true);
                jLabQuantidade.setVisible(true);
                jComboBoxFornecedor.setEnabled(false);
                break;
            default:
                ocultaCampos();
                jBtnAdicionar.setVisible(false);
                jBtnConfirmarBaixa.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jComboBoxTipoAlteracaoActionPerformed

    private void jBtnConfirmarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarBaixaActionPerformed
        
        int quantAtual = Integer.parseInt(txtQuantEstoque.getText());
        int quantRetirada = Integer.parseInt(txtQuantidade.getText());
        int result = quantAtual - quantRetirada;
        
        ProdutoDAO.BaixaEstoque(result, codDetProd);
        CarregarDadosProduto();
        telaExibeProdutos.TabelaProduto("SELECT * FROM vw_produtos WHERE id_prod = " + codProduto + ";");
    }//GEN-LAST:event_jBtnConfirmarBaixaActionPerformed

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
        idFornecedorComboBox();
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed

    public void CarregarDadosProduto() {
        
        Statement stmt;
        
        try {
            
            String Sql = "SELECT * FROM vw_produtos WHERE idDetProduto = " + codDetProd + ";";
            
            ResultSet rs;            
            stmt = Conexao.getConnection().createStatement();            
            rs = stmt.executeQuery(Sql); 
            
            while(rs.next()){
                
                txtProduto.setText(rs.getString("produto"));
                txtQuantEstoque.setText(String.valueOf(rs.getInt("quantidade")));
                txtPrecoEntrada.setText(String.valueOf(rs.getDouble("precoEntrada")));
                txtPrecoSaida.setText(String.valueOf(rs.getDouble("precoSaida")));
                txtQuantMinima.setText(String.valueOf(rs.getInt("quantidadeMinima")));
                txtModelo.setText(rs.getString("modelo"));
                txtFabricante.setText(rs.getString("fabricante"));                  
            }            
            rs.close();
            stmt.close();
            
        } catch (SQLException ex) {      
            Logger.getLogger(ExibeProdutos.class.getName()).log(Level.SEVERE, null, ex);
            throw new RuntimeException("Erro ao carregar os dados do Produto: ", ex);    
        }        
    }
    
    private void populaComboBoxFornecedor() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfornecedor";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                jComboBoxFornecedor.addItem(rs.getString("fornecedor"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void idFornecedorComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfornecedor where fornecedor = '" + jComboBoxFornecedor.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                codFornecedor = (rs.getInt("id_forn"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnCalcular;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmarBaixa;
    private javax.swing.JComboBox jComboBoxFornecedor;
    private javax.swing.JComboBox jComboBoxTipoAlteracao;
    private javax.swing.JLabel jLabData;
    private javax.swing.JLabel jLabPercentual;
    private javax.swing.JLabel jLabQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser txtDataCadProduto;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPercentual;
    private javax.swing.JTextField txtPrecoEntrada;
    private javax.swing.JTextField txtPrecoSaida;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantEstoque;
    private javax.swing.JTextField txtQuantMinima;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
