package telas;

import atributos.Cliente;
import atributos.Lembrete;
import atributos.Usuario;
import funcoes.ClienteDAO;
import funcoes.Conexao;
import funcoes.FuncoesDiversas;
import static funcoes.FuncoesDiversas.FormataData;
import funcoes.LembreteDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author S015365
 */
public class CadastrarLembrete extends javax.swing.JFrame {

    private PreparedStatement pst;
    
    private int codCli;
    private DetalharCliente detalharCliente;
    /**
     * Creates new form CadastrarLembrete
     */
    public CadastrarLembrete() {
        initComponents();
        jLabCodigo.setVisible(false);
        jLabEmpresa.setVisible(false);
        jLabNCodigo.setVisible(false);
        jLabCodEmpresa.setVisible(false);
        populaComboBox();  
    }
    
    public CadastrarLembrete(int codCliente) {              
        initComponents();
        this.codCli = codCliente;        
        jComboBoxEmpresas.setVisible(false);
        jLabCodEmpresa.setVisible(false);            
        DadosEmpresa();
    }
    
    public CadastrarLembrete(int codCliente, DetalharCliente detalharCliente) {        
        initComponents();
       // this();     
        this.detalharCliente = detalharCliente;       
        this.codCli = codCliente;
        jComboBoxEmpresas.setVisible(false);
        jLabCodEmpresa.setVisible(false);       
        DadosEmpresa();
    }

    private void DadosEmpresa() {

        ArrayList<Cliente> cliente = new ArrayList<Cliente>();
        cliente = ClienteDAO.CarregaNomeCliente(codCli);       

            for (Cliente cli : cliente) {

                jLabCodigo.setText(String.valueOf(cli.getId()));
                jLabEmpresa.setText(cli.getEmpresa());
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabNCodigo = new javax.swing.JLabel();
        jLabCodigo = new javax.swing.JLabel();
        jLabNomeEmpresa = new javax.swing.JLabel();
        jComboBoxEmpresas = new javax.swing.JComboBox();
        jLabEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataLembrete = new com.toedter.calendar.JDateChooser();
        txtHoraLembrete = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoLembrete = new javax.swing.JTextArea();
        jBtnSalvarLembrete = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jLabCodEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lembrete");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabNCodigo.setText("Código:");
        jPanel1.add(jLabNCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabCodigo.setText("codigo");
        jPanel1.add(jLabCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabNomeEmpresa.setText("Empresa:");
        jPanel1.add(jLabNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        jComboBoxEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpresasActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 170, 20));

        jLabEmpresa.setText("empresa");
        jPanel1.add(jLabEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 20));

        jLabel2.setText("Data:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtDataLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, -1));
        jPanel1.add(txtHoraLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 60, -1));

        jLabel3.setText("Hora:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setText("Descrição:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtDescricaoLembrete.setColumns(20);
        txtDescricaoLembrete.setRows(5);
        jScrollPane1.setViewportView(txtDescricaoLembrete);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 289, 191));

        jBtnSalvarLembrete.setText("Salvar");
        jBtnSalvarLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarLembreteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSalvarLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));
        jPanel1.add(jLabCodEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 76, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalvarLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarLembreteActionPerformed
        
        if (!jLabCodEmpresa.getText().isEmpty()) {
            codCli = Integer.parseInt(jLabCodEmpresa.getText());
            System.out.println(codCli);
        }
        
//        try {
            Lembrete lembrete = new Lembrete();
            lembrete.setCodUsuario(Usuario.idUsuario());
            lembrete.setDataLembrete(FormataData(txtDataLembrete.getDate()));            
            lembrete.setHora(FuncoesDiversas.ConverterHora(txtHoraLembrete.getText()));
            lembrete.setDescricao(txtDescricaoLembrete.getText());                    
            lembrete.setCodCliente(codCli);
            System.out.println(codCli);
            LembreteDAO.CadLembrete(lembrete);      
            this.dispose();
            verificaPagina();
           // limparCampos();
            
//        }catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Campo data Inválido!");
//        }
        
    }//GEN-LAST:event_jBtnSalvarLembreteActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jComboBoxEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpresasActionPerformed
        idSetorComboBox();
    }//GEN-LAST:event_jComboBoxEmpresasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        verificaPagina();       
    }//GEN-LAST:event_formWindowClosed

    private void verificaPagina(){
        if ((this.detalharCliente != null)) {
            this.detalharCliente.setEnabled(true);
            this.detalharCliente.toFront();
            this.detalharCliente.TabelaLembrete2(codCli);
        }
    }
    
//    private void limparCampos(){
//        txtDataLembrete = null;
//        txtDescricaoLembrete.setText("");
//        txtHoraLembrete.setText("");
//        jComboBoxEmpresas.setSelectedIndex(0);
//    }
    
    private void populaComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabcliente";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                jComboBoxEmpresas.addItem(rs.getString("empresa"));
            }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void idSetorComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabcliente where empresa = '" + jComboBoxEmpresas.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                jLabCodEmpresa.setText(String.valueOf(rs.getInt("idcliente")));
            }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnSalvarLembrete;
    private javax.swing.JComboBox jComboBoxEmpresas;
    private javax.swing.JLabel jLabCodEmpresa;
    private javax.swing.JLabel jLabCodigo;
    private javax.swing.JLabel jLabEmpresa;
    private javax.swing.JLabel jLabNCodigo;
    private javax.swing.JLabel jLabNomeEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser txtDataLembrete;
    private javax.swing.JTextArea txtDescricaoLembrete;
    private javax.swing.JTextField txtHoraLembrete;
    // End of variables declaration//GEN-END:variables
}
