package telas;

import atributos.Equipamento;
import static atributos.Usuario.idUsuario;
import funcoes.Conexao;
import funcoes.EquipamentoDAO;
import funcoes.LimitarDigitos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Josy
 */
public class CadastrarEquipamento extends javax.swing.JFrame {

    Equipamento equi = new Equipamento();
    private PreparedStatement pst;
    private int codEquipamento;
    private int codFornecedor;
    private int codFabricante;
    private int codModelo;
    private CadastrarEquipCliente telaCadEquipCliente;

    /**
     * Creates new form CadastrarEquipamento
     */
    public CadastrarEquipamento() {
        initComponents();
        populaComboBoxFornecedor();
        populaComboBoxFabricante();
        populaComboBoxModelo();
        populaComboBoxEquipamento();
        txtEquipamento.setVisible(false);
        jBtnCadEquipamento.setVisible(false);
        jBtnCancelarCadEquipamento.setVisible(false);

        txtEquipamento.setDocument(new LimitarDigitos(45));
        
    }

    public CadastrarEquipamento(CadastrarEquipCliente telaCadEquipCli) {
        telaCadEquipCliente = telaCadEquipCli;
        initComponents();
        populaComboBoxFornecedor();
        populaComboBoxFabricante();
        populaComboBoxModelo();
        populaComboBoxEquipamento();
        txtEquipamento.setVisible(false);
        jBtnCadEquipamento.setVisible(false);
        jBtnCancelarCadEquipamento.setVisible(false);

        txtEquipamento.setDocument(new LimitarDigitos(45));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnCadEquipamento = new javax.swing.JButton();
        jBtbNovoEquipamento = new javax.swing.JButton();
        jBtnCancelarCadEquipamento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxFabricante = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox();
        jBtnSair = new javax.swing.JButton();
        jBtnCadastrarEquipamento = new javax.swing.JButton();
        jComboBoxEquipamento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtEquipamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnCadEquipamento.setText("Salvar");
        jBtnCadEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadEquipamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCadEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jBtbNovoEquipamento.setText("Novo");
        jBtbNovoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtbNovoEquipamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtbNovoEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jBtnCancelarCadEquipamento.setText("Cancelar");
        jBtnCancelarCadEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarCadEquipamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelarCadEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jLabel8.setText("Fornecedor:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o fornecedor" }));
        jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, -1));

        jLabel9.setText("Fabricante:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jComboBoxFabricante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o fabricante" }));
        jComboBoxFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFabricanteActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 260, -1));

        jLabel10.setText("Modelo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o modelo" }));
        jComboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeloActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 200, -1));

        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jBtnCadastrarEquipamento.setText("Cadastrar");
        jBtnCadastrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarEquipamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCadastrarEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jComboBoxEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o produto" }));
        jComboBoxEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEquipamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 260, -1));

        jLabel2.setText("Equipamento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel1.add(txtEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 240, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cadastrar Equipamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 23));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leiaute/img2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        this.dispose();
        verificaPagina();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jComboBoxEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEquipamentoActionPerformed
        idEquipamentoComboBox();
    }//GEN-LAST:event_jComboBoxEquipamentoActionPerformed

    private void jBtnCadEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadEquipamentoActionPerformed

        if (EquipamentoDAO.VerificaEquipamento(txtEquipamento.getText()) == false) {

            equi.setTabusuarioIdUsuario(idUsuario());
            equi.setEquipamento(txtEquipamento.getText());
            codEquipamento = EquipamentoDAO.CadEquipamento(equi);

        } else {
            JOptionPane.showMessageDialog(this, "Registro ja cadastrado");
        }

        jBtnCadEquipamento.setVisible(false);
        jBtnCancelarCadEquipamento.setVisible(false);
        jBtbNovoEquipamento.setVisible(true);
        txtEquipamento.setVisible(false);
        jComboBoxEquipamento.setVisible(true);
        jComboBoxEquipamento.removeAllItems();
        populaComboBoxEquipamento();
        jComboBoxEquipamento.setSelectedItem(txtEquipamento.getText());
    }//GEN-LAST:event_jBtnCadEquipamentoActionPerformed

    private void jBtbNovoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtbNovoEquipamentoActionPerformed

        txtEquipamento.setVisible(true);
        jComboBoxEquipamento.setVisible(false);
        jBtnCadEquipamento.setVisible(true);
        jBtnCancelarCadEquipamento.setVisible(true);
        jBtbNovoEquipamento.setVisible(false);
        txtEquipamento.setEnabled(true);
    }//GEN-LAST:event_jBtbNovoEquipamentoActionPerformed

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
        idFornecedorComboBox();
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed

    private void jBtnCancelarCadEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarCadEquipamentoActionPerformed
        jBtnCadEquipamento.setVisible(false);
        jBtnCancelarCadEquipamento.setVisible(false);
        jBtbNovoEquipamento.setVisible(true);
        txtEquipamento.setVisible(false);
        jComboBoxEquipamento.setVisible(true);
    }//GEN-LAST:event_jBtnCancelarCadEquipamentoActionPerformed

    private void jComboBoxFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFabricanteActionPerformed
        idFabricanteComboBox();
    }//GEN-LAST:event_jComboBoxFabricanteActionPerformed

    private void jComboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeloActionPerformed
        idModeloComboBox();
    }//GEN-LAST:event_jComboBoxModeloActionPerformed

    private void jBtnCadastrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarEquipamentoActionPerformed

        if (jComboBoxFornecedor.getSelectedIndex() == 0){
    JOptionPane.showMessageDialog(null, "Selecione um item!");
    return;
        }  
        
           if (jComboBoxEquipamento.getSelectedIndex() == 0){
    JOptionPane.showMessageDialog(null, "Selecione um item!");
    return;
        }
           
              if (jComboBoxFabricante.getSelectedIndex() == 0){
    JOptionPane.showMessageDialog(null, "Selecione um item!");
    return;
        }
              
                 if (jComboBoxModelo.getSelectedIndex() == 0){
    JOptionPane.showMessageDialog(null, "Selecione um item!");
    return;
        } 
                 
        equi.setTabusuarioIdUsuario(idUsuario());
        equi.setCodFornecedor(codFornecedor);
        equi.setCodModelo(codModelo);
        equi.setCodFabricante(codFabricante);

        equi.setCodEquipamento(codEquipamento);

        EquipamentoDAO.CadDetEquipamento(equi);

        txtEquipamento.setVisible(false);
        jComboBoxEquipamento.setVisible(true);

        limparCampos();
        jComboBoxEquipamento.removeAllItems();
        populaComboBoxEquipamento();
        jBtbNovoEquipamento.setVisible(true);
        verificaPagina();
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        
        if (JOptionPane.showConfirmDialog(null, "Deseja continuar cadastrando?", "Confirmar Cadastro", JOptionPane.YES_NO_OPTION) == 1) {           
            verificaPagina();
            this.dispose();
        } else {
            jComboBoxEquipamento.requestFocus();
        }        
    }//GEN-LAST:event_jBtnCadastrarEquipamentoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        verificaPagina();
    }//GEN-LAST:event_formWindowClosed

    private void limparCampos() {
        jComboBoxFabricante.setSelectedIndex(0);
        jComboBoxFornecedor.setSelectedIndex(0);
        jComboBoxModelo.setSelectedIndex(0);
    }

    private void populaComboBoxEquipamento() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabequipamento;";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                jComboBoxEquipamento.addItem(rs.getString("equipamento"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void idEquipamentoComboBox() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabequipamento where equipamento = '" + jComboBoxEquipamento.getSelectedItem() + "';";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                codEquipamento = (rs.getInt("idEquipamento"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void populaComboBoxFornecedor() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfornecedor";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                jComboBoxFornecedor.addItem(rs.getString("fornecedor"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void idFornecedorComboBox() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfornecedor where fornecedor = '" + jComboBoxFornecedor.getSelectedItem() + "';";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                codFornecedor = (rs.getInt("id_forn"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void populaComboBoxFabricante() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfabricante";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                jComboBoxFabricante.addItem(rs.getString("fabricante"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void idFabricanteComboBox() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfabricante where fabricante = '" + jComboBoxFabricante.getSelectedItem() + "';";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                codFabricante = (rs.getInt("idtabFabricante"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void populaComboBoxModelo() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabmodelo";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                jComboBoxModelo.addItem(rs.getString("modelo"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void idModeloComboBox() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabmodelo where modelo = '" + jComboBoxModelo.getSelectedItem() + "';";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                codModelo = (rs.getInt("idtabModelo"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void verificaPagina() {

        if ((this.telaCadEquipCliente != null)) {
            this.telaCadEquipCliente.carregarComboEquipamento();
            this.telaCadEquipCliente.ComboEquipamento(jComboBoxEquipamento.getSelectedItem().toString());
            this.telaCadEquipCliente.setEnabled(true);
            this.telaCadEquipCliente.toFront();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtbNovoEquipamento;
    private javax.swing.JButton jBtnCadEquipamento;
    private javax.swing.JButton jBtnCadastrarEquipamento;
    private javax.swing.JButton jBtnCancelarCadEquipamento;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JComboBox jComboBoxEquipamento;
    private javax.swing.JComboBox jComboBoxFabricante;
    private javax.swing.JComboBox jComboBoxFornecedor;
    private javax.swing.JComboBox jComboBoxModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEquipamento;
    // End of variables declaration//GEN-END:variables
}
