package telas;

import atributos.HistoricoProduto;
import atributos.Produto;
import funcoes.Conexao;
import static funcoes.FuncoesDiversas.FormataData;
import funcoes.HistoricoProdutoDAO;
import funcoes.ProdutoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author S015365
 */
public class CadastrarProduto extends javax.swing.JFrame {

    Produto prod = new Produto();
    private PreparedStatement pst;
    private int codProduto;
    private int codFornecedor;
    private int codFabricante;
    private int codModelo;
    
    /**
     * Creates new form CadastroUsuario
     */
    public CadastrarProduto() {
        initComponents();
        populaComboBoxFornecedor();
        populaComboBoxFabricante();
        populaComboBoxModelo();
        populaComboBoxProduto();
        txtProduto.setVisible(false);
        jBtnCadProduto.setVisible(false);
        jBtnCancelarCadProduto.setVisible(false);
    }
    
    private void limparCampos() {
        txtProduto.setText("");
        txtPrecoEntrada.setText("");
        txtPrecoSaida.setText("");
        txtQuantidade.setText("");
        jComboBoxFabricante.setSelectedIndex(0);
        jComboBoxFornecedor.setSelectedIndex(0);
        jComboBoxModelo.setSelectedIndex(0);
        txtPercentual.setText("");
        txtQuantMinima.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecoSaida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPercentual = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBtnCadastrarProduto = new javax.swing.JButton();
        txtQuantMinima = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jComboBoxProdutos = new javax.swing.JComboBox();
        jBtnCalcularPercentual = new javax.swing.JButton();
        jComboBoxFornecedor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox();
        jBtnCadProduto = new javax.swing.JButton();
        jBtbNovoProduto = new javax.swing.JButton();
        jBtnCancelarCadProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPrecoEntrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxFabricante = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDataCadProduto = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastrar Produto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 27, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Percentual:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 264, -1, 20));
        jPanel1.add(txtPrecoSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 110, -1));

        jLabel8.setText("Valor de Saída:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, 20));
        jPanel1.add(txtPercentual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 120, 20));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jBtnCadastrarProduto.setText("Cadastrar");
        jBtnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));
        jPanel1.add(txtQuantMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 99, -1));

        jLabel11.setText("Quantidade Mínima:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));
        jPanel1.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 116, -1));

        jLabel3.setText("Quantidade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        jPanel1.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 240, -1));

        jComboBoxProdutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o produto" }));
        jComboBoxProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 260, -1));

        jBtnCalcularPercentual.setText("Calcular");
        jBtnCalcularPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularPercentualActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCalcularPercentual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o fornecedor" }));
        jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 200, -1));

        jLabel2.setText("Fornecedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel5.setText("Modelo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o modelo" }));
        jComboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeloActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 200, -1));

        jBtnCadProduto.setText("Salvar");
        jBtnCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jBtbNovoProduto.setText("Novo produto");
        jBtbNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtbNovoProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtbNovoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jBtnCancelarCadProduto.setText("Cancelar");
        jBtnCancelarCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelarCadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel7.setText("Valor de Entrada:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(txtPrecoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 130, -1));

        jLabel6.setText("Fabricante:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jComboBoxFabricante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o fabricante" }));
        jComboBoxFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFabricanteActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 260, 20));

        jLabel10.setText("Peça:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel12.setText("Data:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));
        jPanel1.add(txtDataCadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarProdutoActionPerformed

        HistoricoProduto histProduto = new HistoricoProduto();
        
        prod.setCodModelo(codModelo);
        prod.setCodFabricante(codFabricante);
        prod.setDataCadProduto(FormataData(txtDataCadProduto.getDate()));
        prod.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        prod.setPrecoEntrada(Double.parseDouble(txtPrecoEntrada.getText()));
        prod.setPrecoSaida(Double.parseDouble(txtPrecoSaida.getText())); 
        prod.setCodProduto(codProduto);
        prod.setQuantidadeMinima(Integer.parseInt(txtQuantMinima.getText()));
        
        int codDet = ProdutoDAO.CadDetProduto(prod);
        
        histProduto.setCodDetProduto(codDet);
        histProduto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        histProduto.setValor(Double.parseDouble(txtPrecoEntrada.getText()));
        histProduto.setDataCadProduto(FormataData(txtDataCadProduto.getDate()));
        histProduto.setCodFornecedor(codFornecedor);
        HistoricoProdutoDAO.CadHistoricoProd(histProduto);
             
        txtProduto.setVisible(false);
        jComboBoxProdutos.setVisible(true);
        
        limparCampos(); 
        jComboBoxProdutos.removeAllItems();
        populaComboBoxProduto();
        jBtbNovoProduto.setVisible(true);        
    }//GEN-LAST:event_jBtnCadastrarProdutoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
        idFornecedorComboBox();
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed

    private void jComboBoxFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFabricanteActionPerformed
        idFabricanteComboBox();
    }//GEN-LAST:event_jComboBoxFabricanteActionPerformed

    private void jComboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeloActionPerformed
        idModeloComboBox();
    }//GEN-LAST:event_jComboBoxModeloActionPerformed

    private void jComboBoxProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutosActionPerformed
        idProdutoComboBox();
    }//GEN-LAST:event_jComboBoxProdutosActionPerformed

    private void jBtnCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadProdutoActionPerformed
        
        prod.setIdUsuario(1);
        prod.setProduto(txtProduto.getText());
        codProduto = ProdutoDAO.Cadroduto(prod);
        jBtnCadProduto.setVisible(false);
        jBtnCancelarCadProduto.setVisible(false);
        jBtbNovoProduto.setVisible(false);
        txtProduto.setVisible(false);
        jComboBoxProdutos.setVisible(true);
        jComboBoxProdutos.removeAllItems();
        populaComboBoxProduto();

    }//GEN-LAST:event_jBtnCadProdutoActionPerformed

    private void jBtnCalcularPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularPercentualActionPerformed
        
        float percentual = Float.parseFloat(txtPercentual.getText());
        double precoEntrada = Double.parseDouble(txtPrecoEntrada.getText());
        double resultado = (precoEntrada*percentual)/100;        
        txtPrecoSaida.setText(String.valueOf(precoEntrada + resultado));        
    }//GEN-LAST:event_jBtnCalcularPercentualActionPerformed

    private void jBtbNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtbNovoProdutoActionPerformed
        
        txtProduto.setVisible(true);
        jComboBoxProdutos.setVisible(false);
        jBtnCadProduto.setVisible(true);
        jBtnCancelarCadProduto.setVisible(true);
        jBtbNovoProduto.setVisible(false);
        txtProduto.setEnabled(true);
    }//GEN-LAST:event_jBtbNovoProdutoActionPerformed

    private void jBtnCancelarCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarCadProdutoActionPerformed
        jBtnCadProduto.setVisible(false);
        jBtnCancelarCadProduto.setVisible(false);
        jBtbNovoProduto.setVisible(true);
        txtProduto.setVisible(false);
        jComboBoxProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnCancelarCadProdutoActionPerformed

    private void populaComboBoxProduto() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabproduto;";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                jComboBoxProdutos.addItem(rs.getString("produto"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void idProdutoComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabproduto where produto = '" + jComboBoxProdutos.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                codProduto = (rs.getInt("id_prod"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void populaComboBoxFornecedor() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfornecedor";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                jComboBoxFornecedor.addItem(rs.getString("fornecedor"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void idFornecedorComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfornecedor where fornecedor = '" + jComboBoxFornecedor.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                codFornecedor = (rs.getInt("id_forn"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
   
    private void populaComboBoxFabricante() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfabricante";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                jComboBoxFabricante.addItem(rs.getString("fabricante"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void idFabricanteComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabfabricante where fabricante = '" + jComboBoxFabricante.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                codFabricante = (rs.getInt("idtabFabricante"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void populaComboBoxModelo() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabmodelo";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                jComboBoxModelo.addItem(rs.getString("modelo"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void idModeloComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabmodelo where modelo = '" + jComboBoxModelo.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                codModelo = (rs.getInt("idtabModelo"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtbNovoProduto;
    private javax.swing.JButton jBtnCadProduto;
    private javax.swing.JButton jBtnCadastrarProduto;
    private javax.swing.JButton jBtnCalcularPercentual;
    private javax.swing.JButton jBtnCancelarCadProduto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBoxFabricante;
    private javax.swing.JComboBox jComboBoxFornecedor;
    private javax.swing.JComboBox jComboBoxModelo;
    private javax.swing.JComboBox jComboBoxProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txtDataCadProduto;
    private javax.swing.JTextField txtPercentual;
    private javax.swing.JTextField txtPrecoEntrada;
    private javax.swing.JTextField txtPrecoSaida;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantMinima;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
