package telas;

import atributos.Aluguel;
import atributos.Cliente;
import funcoes.AluguelDAO;
import funcoes.ClienteDAO;
import funcoes.Conexao;
import static funcoes.Conexao.getConnection;
import funcoes.FuncoesDiversas;
import static funcoes.FuncoesDiversas.ConverterData;
import static funcoes.FuncoesDiversas.FormataData;
import funcoes.LimitarDigitos;
import funcoes.ModeloTabela;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Josy
 */
public class DetalharAluguel extends javax.swing.JFrame {

    private PreparedStatement pst;
    Statement stmt;
    private int codCliente;
    private int idAluguel;
    private int idCliente;
    private int idDetAluguel;
    double total;

    /**
     * Creates new form DetalharAluguel
     */
    public DetalharAluguel() {
        initComponents();
        txtDescricao.setDocument(new LimitarDigitos(255));
    }

    public DetalharAluguel(int codAluguel) {
        this.idAluguel = codAluguel;
        initComponents();
        CarregaAluguel();
        ocultaCampos();
        populaComboBoxCliente();
        TabelaEquipamento("SELECT * FROM vw_detaluguel where idtabDetLocacao = " + idAluguel + ";");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBtnEditarAluguel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtDataLocacao = new javax.swing.JLabel();
        jBtnCancelAltAluguel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDataAlterada = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtDataAlteradaDevolucao = new com.toedter.calendar.JDateChooser();
        txtCliente = new javax.swing.JLabel();
        jBtnSalvarAltAluguel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox();
        txtHoraAlterada = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEquipamento = new javax.swing.JTable();
        jBtnAdicionarEquipamento = new javax.swing.JButton();
        jBtnRemoverEquipamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Aluguel");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Gerais"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnEditarAluguel.setText("Editar");
        jBtnEditarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarAluguelActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnEditarAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel8.setText("Hora:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 20));

        jLabel6.setText("Cliente:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        txtHora.setText("hora");
        jPanel2.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 93, 20));

        jLabel5.setText("Descrição:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        txtDataDevolucao.setText("Data devolução");
        jPanel2.add(txtDataDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 118, 20));

        txtTotal.setText("total");
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 107, 20));

        txtDataLocacao.setText("Data locação");
        jPanel2.add(txtDataLocacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, 19));

        jBtnCancelAltAluguel.setText("Cancelar");
        jBtnCancelAltAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelAltAluguelActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancelAltAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabel12.setText("Data Locação:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 20));
        jPanel2.add(txtDataAlterada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, -1));

        jLabel10.setText("Data Devolução:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        txtDescricao.setEditable(false);
        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane4.setViewportView(txtDescricao);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 450, 100));
        jPanel2.add(txtDataAlteradaDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 140, -1));

        txtCliente.setText("cliente");
        jPanel2.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 270, 20));

        jBtnSalvarAltAluguel.setText("Alterar");
        jBtnSalvarAltAluguel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBtnSalvarAltAluguelItemStateChanged(evt);
            }
        });
        jBtnSalvarAltAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarAltAluguelActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSalvarAltAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel9.setText("Total:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, 20));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 290, 20));

        try {
            txtHoraAlterada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtHoraAlterada, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 60, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamentos"));

        jTableEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo det aluguel", "Equipamento", "Modelo", "Fabricante", "Quantidade", "Vr. Locação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEquipamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEquipamento);

        jBtnAdicionarEquipamento.setText("Adicionar");
        jBtnAdicionarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarEquipamentoActionPerformed(evt);
            }
        });

        jBtnRemoverEquipamento.setText("Remover");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableEquipamento, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnRemoverEquipamento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnRemoverEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdicionarEquipamento)
                    .addComponent(jBtnRemoverEquipamento))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBtnAdicionarEquipamento)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRemoverEquipamento))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 550));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRemoverEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverEquipamentoActionPerformed

        if (jTableEquipamento.getRowCount() == 1) {
            JOptionPane.showMessageDialog(null, "Não foi possível excluir o equipamento /n. É preciso que tenha ao menos um equipamento alugado.");
            
        } else {
            int linha = jTableEquipamento.getSelectedRow();
            idDetAluguel = (Integer.parseInt(jTableEquipamento.getValueAt(linha, 0).toString()));
            AluguelDAO.ExcluirDetAluguel(idDetAluguel);
            TabelaEquipamento("SELECT * FROM vw_detaluguel where idtabDetLocacao = " + idAluguel + ";");
        }
    }//GEN-LAST:event_jBtnRemoverEquipamentoActionPerformed

    private void jBtnAdicionarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarEquipamentoActionPerformed
        new AdicionarDetAluguel(idAluguel, this).setVisible(true);
    }//GEN-LAST:event_jBtnAdicionarEquipamentoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        idClienteComboBox();
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jBtnEditarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarAluguelActionPerformed

        jComboBoxCliente.setVisible(true);
        jComboBoxCliente.removeAllItems();
        populaComboBoxCliente();
        jComboBoxCliente.setSelectedItem(txtCliente.getText());
        txtDataAlterada.setVisible(true);
        txtDataAlteradaDevolucao.setVisible(true);
        txtHoraAlterada.setVisible(true);
        jBtnSalvarAltAluguel.setVisible(true);
        jBtnCancelAltAluguel.setVisible(true);

        txtHoraAlterada.setText(txtHora.getText());
        Date d = ConverterData(txtDataLocacao.getText());
        txtDataAlterada.setDate(d);
        Date d2 = ConverterData(txtDataDevolucao.getText());
        txtDataAlteradaDevolucao.setDate(d2);
        CamposEdicao();
    }//GEN-LAST:event_jBtnEditarAluguelActionPerformed

    private void jBtnSalvarAltAluguelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBtnSalvarAltAluguelItemStateChanged

    }//GEN-LAST:event_jBtnSalvarAltAluguelItemStateChanged

    private void jBtnSalvarAltAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarAltAluguelActionPerformed

        Aluguel alug = new Aluguel();

        alug.setTabclienteIdcliente(codCliente);
        alug.setDataAluguel(FormataData(txtDataAlterada.getDate()));
        System.out.println(txtDataAlterada.getDate());
        alug.setDataDevolucao(FormataData(txtDataAlteradaDevolucao.getDate()));
        alug.setDescricaotLocacao(txtDescricao.getText());
        alug.setHora(FuncoesDiversas.ConverterHora(txtHoraAlterada.getText()));

        AluguelDAO.UpdateAluguel(alug, idAluguel);

        CarregaAluguel();
        ocultaCampos();
    }//GEN-LAST:event_jBtnSalvarAltAluguelActionPerformed

    private void jBtnCancelAltAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelAltAluguelActionPerformed
        ocultaCampos();
    }//GEN-LAST:event_jBtnCancelAltAluguelActionPerformed

    public void CarregaAluguel() {

        ArrayList<Aluguel> aluguel = new ArrayList<Aluguel>();
        aluguel = AluguelDAO.CarregaAluguel(idAluguel);

        for (Aluguel al : aluguel) {

            idCliente = al.getTabclienteIdcliente();
            txtDataLocacao.setText(String.valueOf(al.getDataAluguel()));
            txtDataDevolucao.setText(String.valueOf(al.getDataDevolucao()));
            txtTotal.setText(String.valueOf(total));
            txtDescricao.setText(al.getDescricaotLocacao());
            txtHora.setText(String.valueOf(al.getHora()));
        }

        ArrayList<Cliente> cliente = new ArrayList<Cliente>();
        cliente = ClienteDAO.CarregaNomeCliente(idCliente);

        for (Cliente cli : cliente) {
            txtCliente.setText(cli.getEmpresa());
        }
    }

    public void TabelaEquipamento(String Sql) {

        try {

            total = 0;
            stmt = getConnection().createStatement();
            ArrayList dados = new ArrayList();
            String[] Colunas = {"Código", "Equipamento", "Modelo", "Fabricante", "Qtd.", "Vr. Locação", "Total"};

            ResultSet rs;
            rs = stmt.executeQuery(Sql);

            while (rs.next()) {
                double totalEquipamento = rs.getInt("quantEquipamento") * rs.getDouble("valorLocacao");
                dados.add(new Object[]{rs.getObject("idDetLocacao"), rs.getObject("equipamento"),
                    rs.getObject("modelo"), rs.getObject("fabricante"),
                    rs.getObject("quantEquipamento"), rs.getObject("valorLocacao"),
                    totalEquipamento});
                total += totalEquipamento;
            }

            txtTotal.setText(String.valueOf(total));
            for (int i = 0; i < 7; i++) {

                ModeloTabela modelo = new ModeloTabela(dados, Colunas);
                jTableEquipamento.setModel(modelo);
                jTableEquipamento.getColumnModel().getColumn(i).setPreferredWidth(150);
                jTableEquipamento.getColumnModel().getColumn(i).setResizable(false);
                jTableEquipamento.getTableHeader().setReorderingAllowed(false);
                jTableEquipamento.setAutoResizeMode(jTableEquipamento.AUTO_RESIZE_OFF);
                jTableEquipamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DetalharServico.class.getName()).log(Level.SEVERE, null, ex);

        } catch (Exception erro) {
            Logger.getLogger(DetalharServico.class.getName()).log(Level.SEVERE, null, erro);
        }
    }

    private void populaComboBoxCliente() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabcliente";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                jComboBoxCliente.addItem(rs.getString("empresa"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void idClienteComboBox() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabcliente where empresa = '" + jComboBoxCliente.getSelectedItem() + "';";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                codCliente = (rs.getInt("idcliente"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void ocultaCampos() {

        txtDataAlterada.setVisible(false);
        txtDataAlteradaDevolucao.setVisible(false);
        txtHoraAlterada.setVisible(false);
        txtDescricao.setEditable(false);
        jComboBoxCliente.setVisible(false);
        jBtnCancelAltAluguel.setVisible(false);
        jBtnSalvarAltAluguel.setVisible(false);

        txtCliente.setVisible(true);
        txtDataLocacao.setVisible(true);
        txtDataDevolucao.setVisible(true);
        txtHora.setVisible(true);
        jBtnEditarAluguel.setVisible(true);

    }

    public void CamposEdicao() {
        txtCliente.setVisible(false);
        txtDataLocacao.setVisible(false);
        txtDataDevolucao.setVisible(false);
        txtHora.setVisible(false);
        txtDescricao.setEditable(true);
        jBtnEditarAluguel.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionarEquipamento;
    private javax.swing.JButton jBtnCancelAltAluguel;
    private javax.swing.JButton jBtnEditarAluguel;
    private javax.swing.JButton jBtnRemoverEquipamento;
    private javax.swing.JButton jBtnSalvarAltAluguel;
    private javax.swing.JComboBox jComboBoxCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableEquipamento;
    private javax.swing.JLabel txtCliente;
    private com.toedter.calendar.JDateChooser txtDataAlterada;
    private com.toedter.calendar.JDateChooser txtDataAlteradaDevolucao;
    private javax.swing.JLabel txtDataDevolucao;
    private javax.swing.JLabel txtDataLocacao;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JLabel txtHora;
    private javax.swing.JFormattedTextField txtHoraAlterada;
    private javax.swing.JLabel txtTotal;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
