package telas;

import atributos.Cliente;
import atributos.Funcionario;
import atributos.Servico;
import atributos.TipoServico;
import funcoes.ClienteDAO;
import funcoes.Conexao;
import static funcoes.Conexao.getConnection;
import funcoes.DetServicoEquipamentoDAO;
import funcoes.DetServicoFuncionarioDAO;
import funcoes.DetServicoProdutoDAO;
import funcoes.DetServicoTipoDAO;
import funcoes.FuncoesDiversas;
import static funcoes.FuncoesDiversas.ConverterData;
import funcoes.ModeloTabela;
import funcoes.ServicoDAO;
import funcoes.TabelaZebrada;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Josy
 */
public final class DetalharServico extends javax.swing.JFrame {

    
    private PreparedStatement pst;
    private int codCliente;
    private int idServico;
    private int idCliente;
    private int codDetServProduto;
    private int codDetServEquipamento;
    private int codDetServTipoServico;
    private int codDetServFuncionario;
    private double total;
    private double valorMaoObra;
    Statement stmt;
    
    /**
     * Creates new form DetalharServico
     */
    public DetalharServico() {
        initComponents();
    }
    
    public double Total() {
        return total;
    }
    
    public DetalharServico(int codServico) {
        this.idServico = codServico;
        initComponents();
        CarregaServico();
        TabelaProduto("SELECT * FROM vw_detservicoproduto where idservico = " + idServico +";");
        TabelaEquipamento("SELECT * FROM vw_detservequipamento where idservico = " + idServico +";");
        TabelaTipoServico();
        TabelaFuncionario();
        ocultaCampos();  
        ocultaCamposValor();
        
        //Combobox clientes
        uJComboBoxClientes.getEditor().getEditorComponent().addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                if (codCliente == 0 && uJComboBoxClientes.getSelectedIndex() != 0) {
                    JOptionPane.showMessageDialog(null, "Esse registro não encontra-se cadastrado na base de dados.");
                    uJComboBoxClientes.getEditor().getEditorComponent().requestFocus();
                }
            }
        });
        uJComboBoxClientes.setAutocompletar(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtCliente = new javax.swing.JLabel();
        txtDataAlterada = new com.toedter.calendar.JDateChooser();
        txtData = new javax.swing.JLabel();
        jBtnEditarServico = new javax.swing.JButton();
        jBtnSalvarAltServico = new javax.swing.JButton();
        jBtnCancelAltServico = new javax.swing.JButton();
        uJComboBoxClientes = new componentes.UJComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableTipodeServico = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jBtnRemoverDetServTipoServico = new javax.swing.JButton();
        jBtnAdicionarDetServTipoServico = new javax.swing.JButton();
        jPanelPecaEEquip = new javax.swing.JPanel();
        jPanelPecas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePecas = new javax.swing.JTable();
        jBtnAdicionarPeca = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jPanelEquipamento = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEquipamento = new javax.swing.JTable();
        jBtnAdicionarEquipamento = new javax.swing.JButton();
        jBtnRemoverEquipamento = new javax.swing.JButton();
        jPanelFuncionarioValor = new javax.swing.JPanel();
        jPanelFuncionario = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        jBtnAdicionarFuncionario = new javax.swing.JButton();
        jBtnRemoverFuncionario = new javax.swing.JButton();
        jPanelValor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnAlterarMaoObra = new javax.swing.JButton();
        jBtnCancelAltValor = new javax.swing.JButton();
        jBtnEditarValor = new javax.swing.JButton();
        txtMaoObra = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(860, 800));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Serviço"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Cliente:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 30, -1, 20));

        jLabel12.setText("Data:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 30, 20));

        jLabel5.setText("Descrição:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricao.setRows(5);
        jScrollPane4.setViewportView(txtDescricao);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 620, 90));

        txtCliente.setText("cliente");
        jPanel3.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 310, 20));
        jPanel3.add(txtDataAlterada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 140, -1));

        txtData.setText("data");
        jPanel3.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, 20));

        jBtnEditarServico.setText("Editar");
        jBtnEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarServicoActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnEditarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jBtnSalvarAltServico.setText("Alterar");
        jBtnSalvarAltServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBtnSalvarAltServicoItemStateChanged(evt);
            }
        });
        jBtnSalvarAltServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarAltServicoActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnSalvarAltServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        jBtnCancelAltServico.setText("Cancelar");
        jBtnCancelAltServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelAltServicoActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnCancelAltServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        uJComboBoxClientes.setEditable(true);
        uJComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uJComboBoxClientesActionPerformed(evt);
            }
        });
        jPanel3.add(uJComboBoxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 340, -1));

        jPanel13.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 800, 210));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tipo Serviço"));

        jTableTipodeServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTipodeServico.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTableTipodeServico);

        jLabel10.setText("Tipo:");

        jBtnRemoverDetServTipoServico.setText("Remover");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableTipodeServico, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnRemoverDetServTipoServico, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnRemoverDetServTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverDetServTipoServicoActionPerformed(evt);
            }
        });

        jBtnAdicionarDetServTipoServico.setText("Adicionar");
        jBtnAdicionarDetServTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarDetServTipoServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnRemoverDetServTipoServico)
                            .addComponent(jBtnAdicionarDetServTipoServico))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jBtnAdicionarDetServTipoServico)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRemoverDetServTipoServico)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel13.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 800, 190));

        jTabbedPane1.addTab("Serviço", new javax.swing.ImageIcon(getClass().getResource("/imagens/servicos.png")), jPanel13); // NOI18N

        jPanelPecas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Peças"));

        jTablePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id det serv produto", "Peça", "Modelo", "Fabricante", "Valor Unit", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePecas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePecas);

        jBtnAdicionarPeca.setText("Adicionar");
        jBtnAdicionarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarPecaActionPerformed(evt);
            }
        });

        jBtnRemover.setText("Remover");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTablePecas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnRemover, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPecasLayout = new javax.swing.GroupLayout(jPanelPecas);
        jPanelPecas.setLayout(jPanelPecasLayout);
        jPanelPecasLayout.setHorizontalGroup(
            jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPecasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdicionarPeca)
                    .addComponent(jBtnRemover))
                .addContainerGap())
        );
        jPanelPecasLayout.setVerticalGroup(
            jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPecasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPecasLayout.createSequentialGroup()
                        .addComponent(jBtnAdicionarPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRemover)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Equipamentos"));

        jTableEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id det servico equipamento", "Equipamento", "Modelo", "Fabricante"
            }
        ));
        jTableEquipamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEquipamento);

        jBtnAdicionarEquipamento.setText("Adicionar");
        jBtnAdicionarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarEquipamentoActionPerformed(evt);
            }
        });

        jBtnRemoverEquipamento.setText("Remover");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableEquipamento, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnRemoverEquipamento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnRemoverEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEquipamentoLayout = new javax.swing.GroupLayout(jPanelEquipamento);
        jPanelEquipamento.setLayout(jPanelEquipamentoLayout);
        jPanelEquipamentoLayout.setHorizontalGroup(
            jPanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipamentoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdicionarEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnRemoverEquipamento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelEquipamentoLayout.setVerticalGroup(
            jPanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEquipamentoLayout.createSequentialGroup()
                        .addComponent(jBtnAdicionarEquipamento)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRemoverEquipamento)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPecaEEquipLayout = new javax.swing.GroupLayout(jPanelPecaEEquip);
        jPanelPecaEEquip.setLayout(jPanelPecaEEquipLayout);
        jPanelPecaEEquipLayout.setHorizontalGroup(
            jPanelPecaEEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPecaEEquipLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelPecaEEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPecaEEquipLayout.setVerticalGroup(
            jPanelPecaEEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPecaEEquipLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanelPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Peças e Equipamento", jPanelPecaEEquip);

        jPanelFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Funcionários"));

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Funcionário"
            }
        ));
        jTableFuncionario.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableFuncionario);

        jBtnAdicionarFuncionario.setText("Adicionar");
        jBtnAdicionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarFuncionarioActionPerformed(evt);
            }
        });

        jBtnRemoverFuncionario.setText("Remover");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableFuncionario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnRemoverFuncionario, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFuncionarioLayout = new javax.swing.GroupLayout(jPanelFuncionario);
        jPanelFuncionario.setLayout(jPanelFuncionarioLayout);
        jPanelFuncionarioLayout.setHorizontalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnRemoverFuncionario)
                    .addComponent(jBtnAdicionarFuncionario))
                .addGap(20, 20, 20))
        );
        jPanelFuncionarioLayout.setVerticalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                        .addComponent(jBtnAdicionarFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRemoverFuncionario)
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelValor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Valores"));

        jLabel4.setText("Total serviço:");

        txtTotal.setText("total");

        jLabel1.setText("Mão de Obra:");

        jBtnAlterarMaoObra.setText("Alterar");
        jBtnAlterarMaoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarMaoObraActionPerformed(evt);
            }
        });

        jBtnCancelAltValor.setText("Cancelar");
        jBtnCancelAltValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelAltValorActionPerformed(evt);
            }
        });

        jBtnEditarValor.setText("Editar");
        jBtnEditarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelValorLayout = new javax.swing.GroupLayout(jPanelValor);
        jPanelValor.setLayout(jPanelValorLayout);
        jPanelValorLayout.setHorizontalGroup(
            jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelValorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelValorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnEditarValor)
                    .addComponent(jBtnAlterarMaoObra)
                    .addComponent(jBtnCancelAltValor))
                .addGap(24, 24, 24))
        );
        jPanelValorLayout.setVerticalGroup(
            jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(jPanelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnEditarValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterarMaoObra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCancelAltValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFuncionarioValorLayout = new javax.swing.GroupLayout(jPanelFuncionarioValor);
        jPanelFuncionarioValor.setLayout(jPanelFuncionarioValorLayout);
        jPanelFuncionarioValorLayout.setHorizontalGroup(
            jPanelFuncionarioValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioValorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelFuncionarioValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelFuncionarioValorLayout.setVerticalGroup(
            jPanelFuncionarioValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioValorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funionário e Valor", jPanelFuncionarioValor);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 520));

        jLabel32.setFont(new java.awt.Font("Raavi", 1, 18)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servicos.png"))); // NOI18N
        jLabel32.setText("Serviço");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leiaute/img3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 140));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAdicionarDetServTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarDetServTipoServicoActionPerformed
        new AdicionarDetServTipoServico(idServico, this).setVisible(true);
    }//GEN-LAST:event_jBtnAdicionarDetServTipoServicoActionPerformed

    private void jBtnRemoverDetServTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverDetServTipoServicoActionPerformed
        int linha = jTableTipodeServico.getSelectedRow();
        codDetServTipoServico = (Integer.parseInt(jTableTipodeServico.getValueAt(linha, 0).toString()));
        DetServicoTipoDAO.ExcluirDetServTipoServico(codDetServTipoServico);
        TabelaTipoServico();
    }//GEN-LAST:event_jBtnRemoverDetServTipoServicoActionPerformed

    private void jBtnEditarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarValorActionPerformed
        valorMaoObra = Double.parseDouble(txtMaoObra.getText());
        jBtnEditarValor.setVisible(false);
        txtMaoObra.setEditable(true);
        jBtnAlterarMaoObra.setVisible(true);
        jBtnCancelAltValor.setVisible(true);
    }//GEN-LAST:event_jBtnEditarValorActionPerformed

    private void jBtnCancelAltValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelAltValorActionPerformed
        ocultaCamposValor();
    }//GEN-LAST:event_jBtnCancelAltValorActionPerformed

    private void jBtnAlterarMaoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarMaoObraActionPerformed
        double maoObra = Double.parseDouble(txtMaoObra.getText());
        total = Double.parseDouble(txtTotal.getText());
        total -= valorMaoObra;
        total += maoObra;
        ServicoDAO.UpdateMaoObraServico(idServico, maoObra);
        ServicoDAO.UpdateTotalServico(idServico, total);
        ocultaCamposValor();
        CarregaServico();
    }//GEN-LAST:event_jBtnAlterarMaoObraActionPerformed

    private void jBtnRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverFuncionarioActionPerformed
        int linha = jTableFuncionario.getSelectedRow();
        codDetServFuncionario = (Integer.parseInt(jTableFuncionario.getValueAt(linha, 0).toString()));
        DetServicoFuncionarioDAO.ExcluirDetServFuncionario(codDetServFuncionario);
        TabelaFuncionario();
    }//GEN-LAST:event_jBtnRemoverFuncionarioActionPerformed

    private void jBtnAdicionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarFuncionarioActionPerformed
        new AdicionarDetServFuncionario(idServico, this).setVisible(true);
    }//GEN-LAST:event_jBtnAdicionarFuncionarioActionPerformed

    private void jBtnRemoverEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverEquipamentoActionPerformed

        int linha = jTableEquipamento.getSelectedRow();
        codDetServEquipamento = (Integer.parseInt(jTableEquipamento.getValueAt(linha, 0).toString()));
        DetServicoEquipamentoDAO.ExcluirDetServEquipamento(codDetServEquipamento);
        TabelaEquipamento("SELECT * FROM vw_detservequipamento where idservico = " + idServico +";");
    }//GEN-LAST:event_jBtnRemoverEquipamentoActionPerformed

    private void jBtnAdicionarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarEquipamentoActionPerformed
        new AdicionarDetServEquipamento(idServico, this).setVisible(true);
    }//GEN-LAST:event_jBtnAdicionarEquipamentoActionPerformed

    private void jBtnCancelAltServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelAltServicoActionPerformed
        ocultaCampos();
    }//GEN-LAST:event_jBtnCancelAltServicoActionPerformed

    private void jBtnSalvarAltServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarAltServicoActionPerformed
        Servico serv = new Servico();
        serv.setCodCliente(codCliente);
        serv.setDescricaoServico(txtDescricao.getText());
        serv.setDataServico(FuncoesDiversas.FormataData(txtDataAlterada.getDate()));

        ServicoDAO.UpdateServico(serv, idServico);
        CarregaServico();
        ocultaCampos();
    }//GEN-LAST:event_jBtnSalvarAltServicoActionPerformed

    private void jBtnSalvarAltServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBtnSalvarAltServicoItemStateChanged

    }//GEN-LAST:event_jBtnSalvarAltServicoItemStateChanged

    private void jBtnEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarServicoActionPerformed

        uJComboBoxClientes.setVisible(true);
        uJComboBoxClientes.removeAllItems();
        carregarComboClientes();
        uJComboBoxClientes.setSelectedItem(txtCliente.getText());
        txtDataAlterada.setVisible(true);
        jBtnSalvarAltServico.setVisible(true);
        jBtnCancelAltServico.setVisible(true);

        Date d = ConverterData(txtData.getText());
        txtDataAlterada.setDate(d);
        CamposEdicao();
    }//GEN-LAST:event_jBtnEditarServicoActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed

        int linha = jTablePecas.getSelectedRow();

        codDetServProduto = (Integer.parseInt(jTablePecas.getValueAt(linha, 0).toString()));

        int quant = Integer.parseInt(jTablePecas.getValueAt(linha, 5).toString());
        double precoUnit = Double.parseDouble(jTablePecas.getValueAt(linha, 4).toString());
        double totalPeca = quant * precoUnit;

        double totalGeral = Double.parseDouble(txtTotal.getText());
        double resultado = totalGeral - totalPeca;
        ServicoDAO.UpdateTotalServico(idServico, resultado);
        DetServicoProdutoDAO.ExcluirDetServProduto(codDetServProduto);
        //  txtTotal.setText(String.valueOf(resultado));
        CarregaServico();
        TabelaProduto("SELECT * FROM vw_detservicoproduto where idservico = " + idServico + ";");

    }//GEN-LAST:event_jBtnRemoverActionPerformed

    private void jBtnAdicionarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarPecaActionPerformed
        new AdicionaDetServProduto(idServico, this).setVisible(true);
        total = Double.parseDouble(txtTotal.getText());
    }//GEN-LAST:event_jBtnAdicionarPecaActionPerformed

    private void uJComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uJComboBoxClientesActionPerformed
        codCliente = 0;
        idClienteComboBox();
    }//GEN-LAST:event_uJComboBoxClientesActionPerformed

    public void ocultaCampos() {
        uJComboBoxClientes.setVisible(false);
        txtDataAlterada.setVisible(false);
        jBtnSalvarAltServico.setVisible(false);
        jBtnCancelAltServico.setVisible(false);
        jBtnEditarServico.setVisible(true);
        txtCliente.setVisible(true);
        txtData.setVisible(true);
        txtDescricao.setEditable(false);
    }
    
    public void ocultaCamposValor() {
        jBtnEditarValor.setVisible(true);
        txtMaoObra.setEditable(false);
        jBtnAlterarMaoObra.setVisible(false);
        jBtnCancelAltValor.setVisible(false);
    }
    
    public void CamposEdicao() {
        txtCliente.setVisible(false);
        txtData.setVisible(false);
        txtDescricao.setEditable(true);
        jBtnEditarServico.setVisible(false);
    }
    
    public void CarregaServico() {
        
        ArrayList<Servico> servico = new ArrayList<Servico>();
        servico = ServicoDAO.CarregaServico(idServico);
        
        for (Servico serv : servico) {
            
            idCliente = serv.getCodCliente();
            txtData.setText(String.valueOf(serv.getDataServico()));
            txtTotal.setText(String.valueOf(serv.getPreco()));
            txtDescricao.setText(serv.getDescricaoServico());
            txtMaoObra.setText(String.valueOf(serv.getMaoDeObra()));
        }
               
        ArrayList<Cliente> cliente = new ArrayList<Cliente>();
        cliente = ClienteDAO.CarregaNomeCliente(idCliente);
        
        for (Cliente cli : cliente) {
            
            txtCliente.setText(cli.getEmpresa());
        }        
    }
    
    public void TabelaProduto(String Sql) {
        
        try { 
            
            stmt = getConnection().createStatement();
            ArrayList dados = new ArrayList();               
            String [] Colunas = {"Código","Peça", "Modelo", "Fabricante","Valor Unit","Quantidade"};
               
            ResultSet rs;
            rs = stmt.executeQuery(Sql);
            
                while(rs.next()) {
                    dados.add(new Object[] { 
                        rs.getObject("iddetServico_produto"),
                        rs.getObject("produto"),                                            
                        rs.getObject("modelo"),
                        rs.getObject("fabricante"),                                             
                        rs.getObject("precoSaida"), 
                        rs.getObject("quantidadeComprada"),
                    });            
                }

                for (int i = 0; i < 6; i++) {
                    
                    ModeloTabela modelo = new ModeloTabela(dados, Colunas);
                    jTablePecas.setModel(modelo);
                    
                    TableCellRenderer renderer = new TabelaZebrada();
                    jTablePecas.setDefaultRenderer(Object.class, renderer);
                    jTablePecas.getColumnModel().getColumn(0).setMaxWidth(0);
                    jTablePecas.getColumnModel().getColumn(0).setMinWidth(0);
                    jTablePecas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                    jTablePecas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
                    
                    jTablePecas.getColumnModel().getColumn(1).setPreferredWidth(200);
                    jTablePecas.getColumnModel().getColumn(2).setPreferredWidth(200);
                    jTablePecas.getColumnModel().getColumn(3).setPreferredWidth(200);
                    jTablePecas.getColumnModel().getColumn(4).setPreferredWidth(100);
                    jTablePecas.getColumnModel().getColumn(5).setPreferredWidth(100);
                    
                    jTablePecas.getColumnModel().getColumn(i).setResizable(false);
                    jTablePecas.getTableHeader().setReorderingAllowed(false);
                    jTablePecas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                }
                    
        } catch (SQLException ex) {
            Logger.getLogger(DetalharServico.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (Exception erro) {
            Logger.getLogger(DetalharServico.class.getName()).log(Level.SEVERE, null, erro);
        }        
    }
    
    
    public void TabelaEquipamento(String Sql) {
        
        try { 
            
            stmt = getConnection().createStatement();
            ArrayList dados = new ArrayList();               
            String [] Colunas = {"Código","Equipamento", "Modelo", "Fabricante"};
               
            ResultSet rs;
            rs = stmt.executeQuery(Sql);
            
                while(rs.next()) {
                    dados.add(new Object[] { rs.getObject("iddetServico_Equipamento"),rs.getObject("equipamento"),
                                             rs.getObject("modelo"),rs.getObject("fabricante")});            
                }

                for (int i = 0; i < 4; i++) {
                    
                    ModeloTabela modelo = new ModeloTabela(dados, Colunas);
                    jTableEquipamento.setModel(modelo);
                    jTableEquipamento.getColumnModel().getColumn(i).setResizable(false);
                    TableCellRenderer renderer = new TabelaZebrada();
                    jTableEquipamento.setDefaultRenderer(Object.class, renderer);
                    
                    jTableEquipamento.getColumnModel().getColumn(0).setMaxWidth(0);
                    jTableEquipamento.getColumnModel().getColumn(0).setMinWidth(0);
                    jTableEquipamento.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                    jTableEquipamento.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
                    
                    jTableEquipamento.getColumnModel().getColumn(1).setPreferredWidth(200);
                    jTableEquipamento.getColumnModel().getColumn(2).setPreferredWidth(200);
                    jTableEquipamento.getColumnModel().getColumn(3).setPreferredWidth(200);
                    jTableEquipamento.getTableHeader().setReorderingAllowed(false);
                    jTableEquipamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                }
                    
        } catch (SQLException ex) {
            Logger.getLogger(DetalharServico.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (Exception erro) {
            Logger.getLogger(DetalharServico.class.getName()).log(Level.SEVERE, null, erro);
        }        
    }
    
    public void TabelaTipoServico() {
        
        ((DefaultTableModel) jTableTipodeServico.getModel()).setNumRows(0);
        jTableTipodeServico.updateUI();
        ArrayList<TipoServico> tipoServ = new ArrayList<TipoServico>();
        tipoServ = DetServicoTipoDAO.CarregaDetServicoTipoServico(idServico);
        
        try { 
            
            DefaultTableModel dtm = (DefaultTableModel) jTableTipodeServico.getModel();
                   
            for(TipoServico tServ : tipoServ) {
                dtm.addRow(new Object[] {
                                        String.valueOf(tServ.getIdTipoServico()),
                                                       tServ.getTipo()});
            }
        
            TableCellRenderer renderer = new TabelaZebrada();
            jTableTipodeServico.setDefaultRenderer(Object.class, renderer);
            //pog oculta coluna jtable
            jTableTipodeServico.getColumnModel().getColumn( 0 ).setMaxWidth( 0 );  
            jTableTipodeServico.getColumnModel().getColumn( 0 ).setMinWidth( 0 );  
            jTableTipodeServico.getTableHeader().getColumnModel().getColumn( 0 ).setMaxWidth( 0 );  
            jTableTipodeServico.getTableHeader().getColumnModel().getColumn( 0 ).setMinWidth( 0 );  
        } catch (Exception erro) {
            Logger.getLogger(DetalharCliente.class.getName()).log(Level.SEVERE, null, erro);
        }          
    } 
    
    public void TabelaFuncionario() {
        
        ((DefaultTableModel) jTableFuncionario.getModel()).setNumRows(0);
        jTableFuncionario.updateUI();
        ArrayList<Funcionario> funcionario = new ArrayList<Funcionario>();
        funcionario = DetServicoFuncionarioDAO.CarregaDetServFuncionario(idServico);
        
        try { 
            
            DefaultTableModel dtm = (DefaultTableModel) jTableFuncionario.getModel();
                   
            for(Funcionario func : funcionario) {
                dtm.addRow(new Object[] {
                                        String.valueOf(func.getId()),
                                                       func.getFuncionario(),
                                                       func.getCpf()});
            }
        
            TableCellRenderer renderer = new TabelaZebrada();
            jTableFuncionario.setDefaultRenderer(Object.class, renderer);      
            
            jTableFuncionario.getColumnModel().getColumn( 0 ).setMaxWidth( 0 );  
            jTableFuncionario.getColumnModel().getColumn( 0 ).setMinWidth( 0 );  
            jTableFuncionario.getTableHeader().getColumnModel().getColumn( 0 ).setMaxWidth( 0 );  
            jTableFuncionario.getTableHeader().getColumnModel().getColumn( 0 ).setMinWidth( 0 );  
        } catch (Exception erro) {
            Logger.getLogger(DetalharCliente.class.getName()).log(Level.SEVERE, null, erro);
        }          
    } 
    
    private void carregarComboClientes() {

        uJComboBoxClientes.clear();

        uJComboBoxClientes.addItem("Selecione o Cliente");
        ArrayList<Cliente> cliente = new ArrayList<Cliente>();
        cliente = ClienteDAO.ComboCliente();

        for (Cliente cli : cliente) {
            uJComboBoxClientes.addItem(cli.getEmpresa(), cli);
        }
    }
    
    private void idClienteComboBox() {
        
        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabcliente where empresa = '" + uJComboBoxClientes.getSelectedItem()+ "';";
        
        try{
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                codCliente = (rs.getInt("idcliente"));
            }
            
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionarDetServTipoServico;
    private javax.swing.JButton jBtnAdicionarEquipamento;
    private javax.swing.JButton jBtnAdicionarFuncionario;
    private javax.swing.JButton jBtnAdicionarPeca;
    private javax.swing.JButton jBtnAlterarMaoObra;
    private javax.swing.JButton jBtnCancelAltServico;
    private javax.swing.JButton jBtnCancelAltValor;
    private javax.swing.JButton jBtnEditarServico;
    private javax.swing.JButton jBtnEditarValor;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JButton jBtnRemoverDetServTipoServico;
    private javax.swing.JButton jBtnRemoverEquipamento;
    private javax.swing.JButton jBtnRemoverFuncionario;
    private javax.swing.JButton jBtnSalvarAltServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEquipamento;
    private javax.swing.JPanel jPanelFuncionario;
    private javax.swing.JPanel jPanelFuncionarioValor;
    private javax.swing.JPanel jPanelPecaEEquip;
    private javax.swing.JPanel jPanelPecas;
    private javax.swing.JPanel jPanelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEquipamento;
    private javax.swing.JTable jTableFuncionario;
    private javax.swing.JTable jTablePecas;
    private javax.swing.JTable jTableTipodeServico;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtData;
    private com.toedter.calendar.JDateChooser txtDataAlterada;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtMaoObra;
    private javax.swing.JLabel txtTotal;
    private componentes.UJComboBox uJComboBoxClientes;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
