package telas;

import atributos.Cliente;
import funcoes.ClienteDAO;
import funcoes.Conexao;
import static funcoes.Conexao.getConnection;
import funcoes.ModeloTabela;
import funcoes.TabelaZebrada;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author S015365 pfc2senai@gmail.com
 *
 */
public final class ExibeCliente extends javax.swing.JFrame {

    Statement stmt;
    Cliente cliente = new Cliente();
    private static int indice;
    private static int idCntato;
    private PreparedStatement pst;
    private int codSetor;
    private int linhaTabela;
    String opcaoPesquisa = "empresa";
    private Menu telaMenu;

    /**
     * Creates new form CadastroDeFuncionarios
     */
    public ExibeCliente() {
        initComponents();
        populaComboBox();
        botoes();
        TabelaCliente("select  * from vw_cliente;");
    }
    
    public ExibeCliente(Menu menu) {
        this.telaMenu = menu;
        initComponents();
        populaComboBox();
        botoes();
        TabelaCliente("select  * from vw_cliente;");
    }

    public static int GetIndice() {
        return indice;
    }
    
    private void botoes() {
        
        jBtnLembrete.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnLembrete.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnRotinaContato.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnRotinaContato.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnEditar.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnEditar.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnCadastrarNovoCliente.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnCadastrarNovoCliente.setHorizontalTextPosition(SwingConstants.CENTER);
    }

    public boolean CodigoCliente() {

        boolean valida = false;

        if (jTableListarClientes.getSelectedRow() != -1) {
            valida = true;
            //this.dispose();
            int linha = jTableListarClientes.getSelectedRow();
            indice = (Integer.parseInt(jTableListarClientes.getValueAt(linha, 0).toString()));
        } else {
            JOptionPane.showMessageDialog(null, "Primeiro selecione um registro.");
        }
        return valida;
    }

    public void TabelaCliente(String Sql) {

        try {

            stmt = getConnection().createStatement();
            ArrayList dados = new ArrayList();
            String[] Colunas = {"Código", "Empresa", "CNPJ", "Setor", "Estado"};

            ResultSet rs;
            rs = stmt.executeQuery(Sql);

            while (rs.next()) {
                dados.add(new Object[]{
                    rs.getObject("idCliente"), 
                    rs.getObject("empresa"),
                    rs.getObject("cnpj"), 
                    rs.getObject("setor"),
                    rs.getObject("estado")});
            }

            for (int i = 0; i < 5; i++) {
                
                ModeloTabela modelo = new ModeloTabela(dados, Colunas);
                jTableListarClientes.setModel(modelo);
                
                TableCellRenderer renderer = new TabelaZebrada();
                jTableListarClientes.setDefaultRenderer(Object.class, renderer);
                
                jTableListarClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
                jTableListarClientes.getColumnModel().getColumn(1).setPreferredWidth(200);
                jTableListarClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
                jTableListarClientes.getColumnModel().getColumn(3).setPreferredWidth(80);
                jTableListarClientes.getColumnModel().getColumn(4).setPreferredWidth(10); 
                jTableListarClientes.getColumnModel().getColumn(i).setResizable(false);
                jTableListarClientes.getTableHeader().setReorderingAllowed(false);
              //  jTableListarClientes.setAutoResizeMode(jTableListarClientes.AUTO_RESIZE_OFF);
                jTableListarClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ExibeCliente.class.getName()).log(Level.SEVERE, null, ex);

        } catch (Exception erro) {
            Logger.getLogger(ExibeCliente.class.getName()).log(Level.SEVERE, null, erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jComboBoxOpcaoPesquisa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarClientes = new javax.swing.JTable();
        jBtnCadastrarNovoCliente = new javax.swing.JButton();
        jBtnRotinaContato = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSetores = new javax.swing.JComboBox();
        jBtnVoltarMenu = new javax.swing.JButton();
        jBtnBuscar = new javax.swing.JButton();
        jComboUf = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jBtnLembrete = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(223, 237, 253));

        jComboBoxOpcaoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a opção de pesquisa", "Código", "Nome", "CNPJ" }));
        jComboBoxOpcaoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcaoPesquisaActionPerformed(evt);
            }
        });

        jTableListarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableListarClientes);

        jBtnCadastrarNovoCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCadastrarNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente2.fw.png"))); // NOI18N
        jBtnCadastrarNovoCliente.setText("Novo");
        jBtnCadastrarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarNovoClienteActionPerformed(evt);
            }
        });

        jBtnRotinaContato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnRotinaContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1452414361_kontact_1.png"))); // NOI18N
        jBtnRotinaContato.setText("Rotina de Contato");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableListarClientes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnRotinaContato, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnRotinaContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRotinaContatoActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel2.setText("Pesquisar:");

        jLabel4.setText("Filtrar:");

        jComboBoxSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSetoresActionPerformed(evt);
            }
        });

        jBtnVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_rotate_clockwise.png"))); // NOI18N
        jBtnVoltarMenu.setText("Voltar");
        jBtnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarMenuActionPerformed(evt);
            }
        });

        jBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.gif"))); // NOI18N
        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jComboUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CLIENTES");

        jBtnLembrete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnLembrete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadastrarLembrete.png"))); // NOI18N
        jBtnLembrete.setText("Lembrete");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableListarClientes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnLembrete, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLembreteActionPerformed(evt);
            }
        });

        jBtnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente3.fw.png"))); // NOI18N
        jBtnEditar.setText("Detalhar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableListarClientes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jBtnEditar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxSetores, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxOpcaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnBuscar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboUf, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnRotinaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnLembrete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnCadastrarNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnVoltarMenu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpcaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSetores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnCadastrarNovoCliente)
                        .addGap(63, 63, 63)
                        .addComponent(jBtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnLembrete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRotinaContato))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jBtnVoltarMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        if (CodigoCliente()) {
            this.setVisible(false);
            new DetalharCliente(this).setVisible(true);
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLembreteActionPerformed

        if (CodigoCliente()) {
            this.setEnabled(false);
            new CadastrarLembrete(indice, this).setVisible(true);
        }
    }//GEN-LAST:event_jBtnLembreteActionPerformed

    private void jBtnCadastrarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarNovoClienteActionPerformed
        this.setVisible(false);
        new CadastrarCliente(this).setVisible(true);
    }//GEN-LAST:event_jBtnCadastrarNovoClienteActionPerformed

    private void jComboBoxSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSetoresActionPerformed
        
        if (jComboUf.getSelectedIndex() != 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%' "
                    + "and setor = '" + jComboBoxSetores.getSelectedItem().toString() + "' "
                    + "and estado = '" + jComboUf.getSelectedItem().toString() + "';");
        
        }else if (jComboUf.getSelectedIndex() == 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%' "
                    + "and setor = '" + jComboBoxSetores.getSelectedItem().toString() + "' ;");
        
        }
        
        if (jComboUf.getSelectedIndex() != 0 && jComboBoxSetores.getSelectedIndex() == 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%' "
                    + "and estado = '" + jComboUf.getSelectedItem().toString() + "';");
        }
        
        if (jComboUf.getSelectedIndex() == 0 && jComboBoxSetores.getSelectedIndex() == 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%';");
        }

    }//GEN-LAST:event_jComboBoxSetoresActionPerformed

    private void jComboBoxOpcaoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcaoPesquisaActionPerformed
        switch (jComboBoxOpcaoPesquisa.getSelectedItem().toString()) {
            case "Código":
                opcaoPesquisa = "idcliente";
                linhaTabela = 0;
                break;
            case "Nome":
                opcaoPesquisa = "empresa";
                linhaTabela = 1;
                break;
            case "CNPJ":
                opcaoPesquisa = "cnpj";
                linhaTabela = 2;
                break;
        }
    }//GEN-LAST:event_jComboBoxOpcaoPesquisaActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed

        int posi = 0;
        boolean valida = false;

        for (int j = 0; j < jTableListarClientes.getRowCount(); j++) {

            if (jComboBoxSetores.getSelectedItem().toString().equalsIgnoreCase(jTableListarClientes.getValueAt(j, 3).toString())) {
                valida = true;
                posi = j;
                break;
            } else {
                valida = false;
            }
        }

        if (valida) {
            jTableListarClientes.getSelectionModel().setSelectionInterval(posi, posi);
            jTableListarClientes.setSelectionBackground(Color.green);
        }
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jComboUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUfActionPerformed

        if (jComboBoxSetores.getSelectedIndex() != 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%' "
                    + "and setor = '" + jComboBoxSetores.getSelectedItem().toString() + "' "
                    + "and estado = '" + jComboUf.getSelectedItem().toString() + "';");
            
        } else if (jComboBoxSetores.getSelectedIndex() == 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%' "
                    + "and estado = '" + jComboUf.getSelectedItem().toString() + "';");
            
        }
        
        if (jComboBoxSetores.getSelectedIndex() != 0 && jComboUf.getSelectedIndex() == 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%' "
                    + "and setor = '" + jComboBoxSetores.getSelectedItem().toString() + "' ;");
        }
        if (jComboBoxSetores.getSelectedIndex() == 0 && jComboUf.getSelectedIndex() == 0) {
            
            TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                    + " like '%" + txtBuscar.getText() + "%';");
        }
    }//GEN-LAST:event_jComboUfActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        TabelaCliente("select  * from vw_cliente where " + opcaoPesquisa
                + " like '%" + txtBuscar.getText() + "%';");
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jBtnRotinaContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRotinaContatoActionPerformed
        if (CodigoCliente()) {
            this.setEnabled(false);
            new CadastrarRotinaContato(indice, this).setVisible(true);
        }             
    }//GEN-LAST:event_jBtnRotinaContatoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        verificaPagina();
    }//GEN-LAST:event_formWindowClosed

    private void jBtnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarMenuActionPerformed
        verificaPagina();
        this.dispose();
    }//GEN-LAST:event_jBtnVoltarMenuActionPerformed

    private void populaComboBox() {

        Connection conexao = Conexao.getConnection();
        ResultSet rs;
        String sql = "select * from tabSetor";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            jComboBoxSetores.addItem("Selecione o Setor");
            while (rs.next()) {
                jComboBoxSetores.addItem(rs.getString("setor"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void verificaPagina() {

        if ((this.telaMenu != null)) {
            this.telaMenu.setVisible(true);
           // this.telaMenu.toFront();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnCadastrarNovoCliente;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnLembrete;
    private javax.swing.JButton jBtnRotinaContato;
    private javax.swing.JButton jBtnVoltarMenu;
    private javax.swing.JComboBox jComboBoxOpcaoPesquisa;
    private javax.swing.JComboBox jComboBoxSetores;
    private javax.swing.JComboBox jComboUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListarClientes;
    private javax.swing.JTextField txtBuscar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
