package telas;


import atributos.Setor;
import funcoes.SetorDAO;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class ExibeSetor extends javax.swing.JFrame {

    Statement stmt ;
    private static int indice;
    /**
     * Creates new form ExibeSetor
     */
    public ExibeSetor() {
        initComponents();
        jBtnNovoSetor.setVisible(false);
        TabelaSetor();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    
    public static int GetIndiceSetor() {         
        return indice;
    }
    
     
    public void TabelaSetor(){
        
        ((DefaultTableModel) jTableListarSetores.getModel()).setNumRows(0);
        jTableListarSetores.updateUI();
        ArrayList<Setor> setores = new ArrayList<Setor>();
        setores = SetorDAO.ListarSetor();
        
        try { 
            
            DefaultTableModel dtm = (DefaultTableModel) jTableListarSetores.getModel();
                   
            for(Setor setor : setores){
                dtm.addRow(new Object[] {String.valueOf(setor.getIdSetor()),setor.getSetor()});
            }
                             
        } catch (Exception erro){
            Logger.getLogger(ExibeSetor.class.getName()).log(Level.SEVERE, null, erro);
        }          
    }    
           
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarSetores = new javax.swing.JTable();
        jBtnExcluirSetor = new javax.swing.JButton();
        jBtnNovoSetor = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        jBtnNovo = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Setores");

        jTableListarSetores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Setor"
            }
        ));
        jTableListarSetores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarSetoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarSetores);
        if (jTableListarSetores.getColumnModel().getColumnCount() > 0) {
            jTableListarSetores.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTableListarSetores.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        jBtnExcluirSetor.setText("Excluir");
        jBtnExcluirSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirSetorActionPerformed(evt);
            }
        });

        jBtnNovoSetor.setText("Cadastrar");
        jBtnNovoSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoSetorActionPerformed(evt);
            }
        });

        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Alterar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jLabel3.setText("Setor:");

        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnSair)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtSetor))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnNovo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnNovoSetor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBtnEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnExcluirSetor))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnNovo)
                        .addComponent(jBtnEditar)
                        .addComponent(jBtnNovoSetor))
                    .addComponent(jBtnExcluirSetor))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBtnSair)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jBtnNovoSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoSetorActionPerformed
        
        Setor setor = new Setor();
        setor.setSetor(txtSetor.getText());
        SetorDAO.CadSetor(setor);
        limparCampos();
        TabelaSetor();
        jBtnNovoSetor.setVisible(false);
        jBtnNovo.setVisible(true);
    }//GEN-LAST:event_jBtnNovoSetorActionPerformed

    private void jBtnExcluirSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirSetorActionPerformed

        SetorDAO.ExcluirSetor(indice);  
        TabelaSetor();
        limparCampos();
    }//GEN-LAST:event_jBtnExcluirSetorActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        
        Setor setor = new Setor();        
        setor.setSetor(txtSetor.getText());
        SetorDAO.UpdateSetor(setor, indice);
        TabelaSetor();
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jTableListarSetoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarSetoresMouseClicked

        int linha = jTableListarSetores.getSelectedRow();
        txtSetor.setText(jTableListarSetores.getValueAt(linha, 1).toString());        
        indice = Integer.parseInt(jTableListarSetores.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_jTableListarSetoresMouseClicked

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        txtSetor.setText("");
        jBtnNovoSetor.setVisible(true);
        jBtnNovo.setVisible(false);
    }//GEN-LAST:event_jBtnNovoActionPerformed
   
    private void limparCampos() {       
        txtSetor.setText("");
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluirSetor;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnNovoSetor;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListarSetores;
    private javax.swing.JTextField txtSetor;
    // End of variables declaration//GEN-END:variables
}
