package telas;

import atributos.Modelo;
import static funcoes.Conexao.getConnection;
import funcoes.ModeloDAO;
import funcoes.ModeloTabela;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Josy
 */
public class OperacaoModelo extends javax.swing.JFrame {

    
    Statement stmt;
    Modelo modelo = new Modelo();
    private static int indice;
    
    
    public OperacaoModelo() {
        initComponents();
        TabelaModelo("select * from tabmodelo;");
        ocultaCampos();
    }

    
    public static int GetIndice() {
        return indice;
    }
    
    private void ocultaCampos() {
        jBtnCadastrarModelo.setVisible(false);
        jBtnAlterarModelo.setVisible(false);
        jBtnCancelarCadModelo.setVisible(false);
        jBtnCancelarAlterarModelo.setVisible(false);
        txtModelo.setEnabled(false);
    }
    
    public void TabelaModelo(String Sql) {

        try {
            
            stmt = getConnection().createStatement();
            ArrayList dados = new ArrayList();
            String[] Colunas = {"Código", "Modelo"};

            ResultSet rs;
            rs = stmt.executeQuery(Sql);

            while (rs.next()) {
                dados.add(new Object[]{
                    rs.getObject("idtabModelo"), 
                    rs.getObject("modelo")});
            }

            for (int i = 0; i < 2; i++) {
                
                ModeloTabela modelo = new ModeloTabela(dados, Colunas);
                jTableListarModelo.setModel(modelo);
                
                jTableListarModelo.getColumnModel().getColumn(0).setMaxWidth(0);
                jTableListarModelo.getColumnModel().getColumn(0).setMinWidth(0);
                jTableListarModelo.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                jTableListarModelo.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
                
                jTableListarModelo.getColumnModel().getColumn(1).setPreferredWidth(200);
                
                jTableListarModelo.getColumnModel().getColumn(i).setResizable(false);
                jTableListarModelo.getTableHeader().setReorderingAllowed(false);
                jTableListarModelo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            }

        } catch (SQLException ex) {
            Logger.getLogger(OperacaoModelo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListarModelo = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jBtnNovoModelo = new javax.swing.JButton();
        jBtnCancelarCadModelo = new javax.swing.JButton();
        jBtnCadastrarModelo = new javax.swing.JButton();
        jBtnAlterarModelo = new javax.swing.JButton();
        jBtnCancelarAlterarModelo = new javax.swing.JButton();
        jBtnEditarModelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableListarModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableListarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarModeloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListarModelo);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel4.setText("Modelo:");

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leiaute/img2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Raavi", 1, 18)); // NOI18N
        jLabel1.setText("Modelos");

        jLabel2.setText("Pesquisar:");

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jBtnNovoModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jBtnNovoModelo.setText("Novo");
        jBtnNovoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoModeloActionPerformed(evt);
            }
        });

        jBtnCancelarCadModelo.setText("Cancelar");
        jBtnCancelarCadModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarCadModeloActionPerformed(evt);
            }
        });

        jBtnCadastrarModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        jBtnCadastrarModelo.setText("Cadastrar");
        jBtnCadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarModeloActionPerformed(evt);
            }
        });

        jBtnAlterarModelo.setText("Alterar");
        jBtnAlterarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarModeloActionPerformed(evt);
            }
        });

        jBtnCancelarAlterarModelo.setText("Cancelar");
        jBtnCancelarAlterarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarAlterarModeloActionPerformed(evt);
            }
        });

        jBtnEditarModelo.setText("Editar");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableListarModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement  !=null}"), jBtnEditarModelo, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnEditarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnEditarModelo)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnCancelarAlterarModelo)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAlterarModelo)
                                .addGap(233, 233, 233))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton7)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCadastrarModelo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNovoModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCancelarCadModelo)))
                        .addGap(0, 109, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnNovoModelo)
                        .addComponent(jBtnCancelarCadModelo)))
                .addGap(18, 18, 18)
                .addComponent(jBtnCadastrarModelo)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnEditarModelo)
                    .addComponent(jBtnCancelarAlterarModelo)
                    .addComponent(jBtnAlterarModelo))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jButton7)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel1)))
                    .addGap(0, 526, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarModeloMouseClicked
        int linha = jTableListarModelo.getSelectedRow();
        if (linha != -1) {
            txtModelo.setText(jTableListarModelo.getValueAt(linha, 1).toString());
            indice = Integer.parseInt(jTableListarModelo.getValueAt(linha, 0).toString());
        }
    }//GEN-LAST:event_jTableListarModeloMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        TabelaModelo("select  * from tabmodelo where modelo "
            + "like '%" + txtBuscar.getText() + "%';");
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBtnNovoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoModeloActionPerformed
        jTableListarModelo.getSelectionModel().clearSelection();
        txtModelo.setText("");
        txtModelo.setEnabled(true);
        jBtnCadastrarModelo.setVisible(true);
        jBtnCancelarCadModelo.setVisible(true);
        jBtnNovoModelo.setVisible(false);

        jBtnEditarModelo.setEnabled(false);
        jTableListarModelo.setEnabled(false);
    }//GEN-LAST:event_jBtnNovoModeloActionPerformed

    private void jBtnCancelarCadModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarCadModeloActionPerformed

        txtModelo.setText("");
        txtModelo.setEnabled(false);
        limparCampos();
        jBtnCancelarCadModelo.setVisible(false);
        jBtnCadastrarModelo.setVisible(false);
        jBtnNovoModelo.setVisible(true);
        // jBtnEditarFabricante.setEnabled(true);
        jTableListarModelo.setEnabled(true);
    }//GEN-LAST:event_jBtnCancelarCadModeloActionPerformed

    private void jBtnCadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarModeloActionPerformed

        if (ModeloDAO.VerificarModelo(txtModelo.getText()) == false) {
            Modelo model = new Modelo();

            model.setModelo(txtModelo.getText());

            ModeloDAO.CadModelo(model);
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
            limparCampos();
            TabelaModelo("select * from tabmodelo;");
            
            jBtnCadastrarModelo.setVisible(false);
            jBtnCancelarCadModelo.setVisible(false);
            jBtnNovoModelo.setVisible(true);
            jTableListarModelo.setEnabled(true);
            txtModelo.setText("");
            txtModelo.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Modelo ja cadastrado");
        }
    }//GEN-LAST:event_jBtnCadastrarModeloActionPerformed

    private void jBtnAlterarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarModeloActionPerformed
        Modelo model = new Modelo();
        model.setModelo(txtModelo.getText());
        ModeloDAO.UpdateModelo(model, GetIndice());        
        jBtnAlterarModelo.setVisible(false);
        jBtnCancelarAlterarModelo.setVisible(false);
        jBtnEditarModelo.setVisible(true);
        jBtnNovoModelo.setEnabled(true);
        txtModelo.setText("");
        txtModelo.setEnabled(false);
        TabelaModelo("select * from tabmodelo");
    }//GEN-LAST:event_jBtnAlterarModeloActionPerformed

    private void jBtnCancelarAlterarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarAlterarModeloActionPerformed
        txtModelo.setText("");
        txtModelo.setEnabled(false);
        jTableListarModelo.getSelectionModel().clearSelection();
        limparCampos();
        jBtnAlterarModelo.setVisible(false);
        jBtnCancelarAlterarModelo.setVisible(false);
        jBtnEditarModelo.setVisible(true);
        jBtnNovoModelo.setEnabled(true);       
    }//GEN-LAST:event_jBtnCancelarAlterarModeloActionPerformed

    private void jBtnEditarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarModeloActionPerformed
        txtModelo.setEnabled(true);
        jBtnEditarModelo.setVisible(false);
        jBtnCancelarAlterarModelo.setVisible(true);
        jBtnAlterarModelo.setVisible(true);
        jBtnNovoModelo.setEnabled(false);
    }//GEN-LAST:event_jBtnEditarModeloActionPerformed

    private void limparCampos() {
        txtModelo.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterarModelo;
    private javax.swing.JButton jBtnCadastrarModelo;
    private javax.swing.JButton jBtnCancelarAlterarModelo;
    private javax.swing.JButton jBtnCancelarCadModelo;
    private javax.swing.JButton jBtnEditarModelo;
    private javax.swing.JButton jBtnNovoModelo;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListarModelo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtModelo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
